#!/usr/bin/env bash
set -Eeuo pipefail

CLAUDE_NPM_PACKAGE_NAME="@anthropic-ai/claude-code"
CLAUDE_CODE_TARGET_VERSION="2.1.142"
CONFIG_DIR="$HOME/.claude-code"
ENV_FILE="$CONFIG_DIR/env"
WRAPPER_DIR="$CONFIG_DIR/bin"
CLAUDE_WRAPPER="$WRAPPER_DIR/claude"
INSTALL_STATE_FILE="$CONFIG_DIR/install-state.json"
CLAUDE_DATA_DIR="$HOME/.claude"
CLAUDE_SETTINGS_JSON="$CLAUDE_DATA_DIR/settings.json"
PROFILE_MARKER_BEGIN="# >>> claude-code bootstrap >>>"
PROFILE_MARKER_END="# <<< claude-code bootstrap <<<"

info() { printf '\033[1;34m[INFO]\033[0m %s\n' "$*"; }
success() { printf '\033[1;32m[OK]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[WARN]\033[0m %s\n' "$*" >&2; }
fatal() { printf '\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2; exit 1; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }

read_user_input() {
  if [[ -t 0 ]]; then
    read "$@"
  elif [[ -r /dev/tty ]]; then
    read "$@" </dev/tty
  else
    read "$@"
  fi
}

confirm() {
  local prompt="$1" reply=""
  read_user_input -r -p "$prompt [y/N]: " reply || true
  [[ "$reply" =~ ^[Yy]$ ]]
}

load_node_runtime() {
  if need_cmd node; then return 0; fi
  export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [[ -s "$NVM_DIR/nvm.sh" ]]; then
    # shellcheck disable=SC1090
    . "$NVM_DIR/nvm.sh" >/dev/null 2>&1 || true
  fi
  need_cmd node
}

state_is_pending() {
  [[ -f "$INSTALL_STATE_FILE" ]] &&
    grep -Eq '"owner"[[:space:]]*:[[:space:]]*"claude-bootstrap"' "$INSTALL_STATE_FILE" 2>/dev/null &&
    grep -Eq '"schemaVersion"[[:space:]]*:[[:space:]]*1' "$INSTALL_STATE_FILE" 2>/dev/null &&
    grep -Eq '"pending"[[:space:]]*:[[:space:]]*true' "$INSTALL_STATE_FILE" 2>/dev/null
}

state_value() {
  local expression="$1"
  [[ -f "$INSTALL_STATE_FILE" ]] || return 0
  load_node_runtime || return 0
  CLAUDE_BOOTSTRAP_STATE_FILE="$INSTALL_STATE_FILE" \
  CLAUDE_BOOTSTRAP_STATE_EXPRESSION="$expression" \
  node <<'NODE'
const fs = require('fs');
let data;
try { data = JSON.parse(fs.readFileSync(process.env.CLAUDE_BOOTSTRAP_STATE_FILE, 'utf8')); }
catch { process.exit(0); }
if (data.owner !== 'claude-bootstrap' || data.schemaVersion !== 1) process.exit(0);
let value = data;
for (const part of process.env.CLAUDE_BOOTSTRAP_STATE_EXPRESSION.split('.')) {
  if (value === null || value === undefined) process.exit(0);
  value = value[part];
}

if (value === true) process.stdout.write('true');
else if (value === false) process.stdout.write('false');
else if (value !== null && value !== undefined) process.stdout.write(String(value));
NODE
}

runtime_inventory_hash() {
  local root="$1"
  load_node_runtime || return 1
  CLAUDE_BOOTSTRAP_RUNTIME_ROOT="$root" node <<'NODE'
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const root = process.env.CLAUDE_BOOTSTRAP_RUNTIME_ROOT;
if (!root || !fs.existsSync(root)) process.exit(1);
const entries = [];
const visit = (absolute, relative) => {
  for (const item of fs.readdirSync(absolute, { withFileTypes: true })) {
    const rel = relative ? `${relative}/${item.name}` : item.name;
    if (rel === '.git' || rel.startsWith('.git/')) continue;
    const full = path.join(absolute, item.name);
    if (/^versions\/node\/[^/]+\/lib\/node_modules\/@anthropic-ai$/.test(rel)) {
      if (item.isDirectory()) visit(full, rel);
      continue;
    }
    if (/^versions\/node\/[^/]+\/lib\/node_modules\/@anthropic-ai\/claude-code(?:\/|$)/.test(rel)) continue;
    if (/^versions\/node\/[^/]+\/bin\/claude$/.test(rel)) continue;
    if (item.isDirectory()) { entries.push(`d:${rel}`); visit(full, rel); }
    else if (item.isSymbolicLink()) entries.push(`l:${rel}:${fs.readlinkSync(full)}`);
    else entries.push(`f:${rel}:${crypto.createHash('sha256').update(fs.readFileSync(full)).digest('hex')}`);
  }
};
visit(root, '');
process.stdout.write(crypto.createHash('sha256').update(entries.sort().join('\n')).digest('hex'));
NODE
}

env_is_managed="0"
env_base_url=""
env_auth_token=""
env_api_key=""
env_model=""
env_custom_model=""
env_discovery=""
env_scrub=""
env_disable_updates=""

load_managed_env() {
  env_is_managed="0"
  env_base_url=""
  env_auth_token=""
  env_api_key=""
  env_model=""
  env_custom_model=""
  env_discovery=""
  env_scrub=""
  env_disable_updates=""
  [[ -f "$ENV_FILE" ]] || return 0
  if ! head -n 1 "$ENV_FILE" 2>/dev/null | grep -Fq 'Generated by claude-bootstrap'; then
    warn "环境文件缺少生成标记，将保留：$ENV_FILE"
    return 0
  fi
  if ! load_node_runtime; then
    warn "未检测到 Node.js，无法安全解析环境文件，将保留：$ENV_FILE"
    return 0
  fi
  local values_tmp=""
  values_tmp="$(mktemp)"
  if ! CLAUDE_BOOTSTRAP_ENV_FILE="$ENV_FILE" node > "$values_tmp" <<'NODE'
const fs = require('fs');
const keys = [
  'ANTHROPIC_BASE_URL', 'ANTHROPIC_AUTH_TOKEN', 'ANTHROPIC_API_KEY', 'ANTHROPIC_MODEL',
  'ANTHROPIC_CUSTOM_MODEL_OPTION', 'CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY',
  'CLAUDE_CODE_SUBPROCESS_ENV_SCRUB', 'DISABLE_UPDATES'
];
const allowed = new Set(keys);
const values = Object.fromEntries(keys.map(key => [key, '']));
const lines = fs.readFileSync(process.env.CLAUDE_BOOTSTRAP_ENV_FILE, 'utf8').split(/\r?\n/);
if (!lines[0] || !lines[0].includes('Generated by claude-bootstrap')) process.exit(2);
const escapedQuote = "'\\''";
for (const line of lines.slice(1)) {
  if (!line) continue;
  let match = line.match(/^export ([A-Z0-9_]+)=(.*)$/);
  if (match) {
    const [, key, raw] = match;
    if (!allowed.has(key)) process.exit(2);
    if (raw.startsWith("'") && raw.endsWith("'")) {
      const inner = raw.slice(1, -1);
      if (inner.split(escapedQuote).join('').includes("'")) process.exit(2);
      values[key] = inner.split(escapedQuote).join("'");
    } else if (/^[01]$/.test(raw)) {
      values[key] = raw;
    } else {
      process.exit(2);
    }
    continue;
  }
  match = line.match(/^unset ([A-Z0-9_]+)$/);
  if (!match || !allowed.has(match[1])) process.exit(2);
  values[match[1]] = '';
}
process.stdout.write(keys.map(key => values[key]).join('\0') + '\0');
NODE
  then
    rm -f "$values_tmp"
    warn "环境文件包含非预期内容，将保留且不会执行：$ENV_FILE"
    return 0
  fi
  env_is_managed="1"
  {
    IFS= read -r -d '' env_base_url || true
    IFS= read -r -d '' env_auth_token || true
    IFS= read -r -d '' env_api_key || true
    IFS= read -r -d '' env_model || true
    IFS= read -r -d '' env_custom_model || true
    IFS= read -r -d '' env_discovery || true
    IFS= read -r -d '' env_scrub || true
    IFS= read -r -d '' env_disable_updates || true
  } < "$values_tmp"
  rm -f "$values_tmp"
}

settings_action() {
  local preview="$1"
  [[ -f "$CLAUDE_SETTINGS_JSON" ]] || return 0
  if ! load_node_runtime; then
    warn "未检测到 Node.js，无法安全解析 settings.json，将保留该文件。"
    return 1
  fi

  CLAUDE_BOOTSTRAP_SETTINGS_FILE="$CLAUDE_SETTINGS_JSON" \
  CLAUDE_BOOTSTRAP_STATE_FILE="$INSTALL_STATE_FILE" \
  CLAUDE_BOOTSTRAP_PREVIEW="$preview" \
  CLAUDE_BOOTSTRAP_ENV_MANAGED="$env_is_managed" \
  CLAUDE_BOOTSTRAP_BASE_URL="$env_base_url" \
  CLAUDE_BOOTSTRAP_AUTH_TOKEN="$env_auth_token" \
  CLAUDE_BOOTSTRAP_API_KEY="$env_api_key" \
  CLAUDE_BOOTSTRAP_MODEL="$env_model" \
  CLAUDE_BOOTSTRAP_CUSTOM_MODEL="$env_custom_model" \
  CLAUDE_BOOTSTRAP_DISCOVERY="$env_discovery" \
  CLAUDE_BOOTSTRAP_SCRUB="$env_scrub" \
  CLAUDE_BOOTSTRAP_DISABLE_UPDATES="$env_disable_updates" \
  node <<'NODE'
const crypto = require('crypto');
const fs = require('fs');
const file = process.env.CLAUDE_BOOTSTRAP_SETTINGS_FILE;
const preview = process.env.CLAUDE_BOOTSTRAP_PREVIEW === '1';
let data;
try { data = JSON.parse(fs.readFileSync(file, 'utf8')); }
catch { console.error(`[WARN] settings.json 不是有效 JSON，将保留：${file}`); process.exit(2); }
if (!data || typeof data !== 'object' || Array.isArray(data)) {
  console.error(`[WARN] settings.json 结构无效，将保留：${file}`);
  process.exit(2);
}
let state = null;
try {
  if (fs.existsSync(process.env.CLAUDE_BOOTSTRAP_STATE_FILE)) {
    const parsed = JSON.parse(fs.readFileSync(process.env.CLAUDE_BOOTSTRAP_STATE_FILE, 'utf8'));
    if (parsed.owner === 'claude-bootstrap' && parsed.schemaVersion === 1) state = parsed;
  }
} catch {}
const env = data.env && typeof data.env === 'object' && !Array.isArray(data.env) ? data.env : {};
let changed = false;
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const removeOrRestore = (key, entry) => {
  if (!Object.hasOwn(env, key)) return;
  let matches = false;
  if (entry.secret) {
    matches = entry.writtenHash && crypto.createHash('sha256').update(String(env[key])).digest('hex') === entry.writtenHash;
  } else {
    matches = Object.hasOwn(entry, 'writtenValue') && same(env[key], entry.writtenValue);
  }
  if (!matches) {
    console.log(`[保留] settings.json env.${key} 已被修改或归属不明`);
    return;
  }
  if (entry.originalKnown && entry.originalPresent && !entry.secret) {
    console.log(`[恢复] settings.json env.${key}`);
    if (!preview) env[key] = entry.originalValue;
  } else {
    console.log(`[删除] settings.json env.${key}`);
    if (!preview) delete env[key];
    if (entry.secret && entry.originalKnown && entry.originalPresent) {
      console.log(`[无法确认] env.${key} 安装前存在，但旧密钥未保存，无法恢复`);
    }
  }
  changed = true;
};
if (state && state.settings && state.settings.managed) {
  for (const [key, entry] of Object.entries(state.settings.managed)) removeOrRestore(key, entry);
  const skip = state.settings.skipWebFetchPreflight;
  if (skip && Object.hasOwn(data, 'skipWebFetchPreflight')) {
    if (Object.hasOwn(skip, 'writtenValue') && same(data.skipWebFetchPreflight, skip.writtenValue)) {
      if (skip.originalKnown && skip.originalPresent) {
        console.log('[恢复] settings.json skipWebFetchPreflight');
        if (!preview) data.skipWebFetchPreflight = skip.originalValue;
      } else if (skip.originalKnown) {
        console.log('[删除] settings.json skipWebFetchPreflight');
        if (!preview) delete data.skipWebFetchPreflight;
      }
      changed = true;
    } else {
      console.log('[保留] settings.json skipWebFetchPreflight 已被修改或归属不明');
    }
  }
} else if (process.env.CLAUDE_BOOTSTRAP_ENV_MANAGED === '1') {
  const legacy = {
    ANTHROPIC_BASE_URL: process.env.CLAUDE_BOOTSTRAP_BASE_URL,
    ANTHROPIC_AUTH_TOKEN: process.env.CLAUDE_BOOTSTRAP_AUTH_TOKEN,
    ANTHROPIC_API_KEY: process.env.CLAUDE_BOOTSTRAP_API_KEY,
    ANTHROPIC_MODEL: process.env.CLAUDE_BOOTSTRAP_MODEL,
    ANTHROPIC_CUSTOM_MODEL_OPTION: process.env.CLAUDE_BOOTSTRAP_CUSTOM_MODEL,
    CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY: process.env.CLAUDE_BOOTSTRAP_DISCOVERY,
    CLAUDE_CODE_SUBPROCESS_ENV_SCRUB: process.env.CLAUDE_BOOTSTRAP_SCRUB,
    DISABLE_UPDATES: process.env.CLAUDE_BOOTSTRAP_DISABLE_UPDATES
  };
  for (const [key, value] of Object.entries(legacy)) {
    if (value !== '' && Object.hasOwn(env, key) && String(env[key]) === value) {
      console.log(`[删除] settings.json env.${key}（旧安装兼容）`);
      if (!preview) delete env[key];
      changed = true;
    } else if (Object.hasOwn(env, key)) {
      console.log(`[保留] settings.json env.${key} 已被修改或无法比对`);
    }
  }
  console.log('[保留] settings.json skipWebFetchPreflight（旧安装无法确认归属）');
} else {
  console.log('[无法确认] 缺少有效状态和 env 文件，保留 settings.json');
}
if (!preview && changed) {
  data.env = env;
  const tmp = `${file}.tmp.${process.pid}`;
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2) + '\n', { mode: 0o600 });
  fs.renameSync(tmp, file);
  try { fs.chmodSync(file, 0o600); } catch {}
}
NODE
}

profile_candidates() {
  local state_profile=""
  state_profile="$(state_value profile.path || true)"
  printf '%s\n' "$state_profile" "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.zshrc" "$HOME/.profile" | awk 'NF && !seen[$0]++'
}

profile_has_block() {
  local file="$1"
  [[ -f "$file" ]] || return 1
  awk -v begin="$PROFILE_MARKER_BEGIN" -v end="$PROFILE_MARKER_END" '
    BEGIN { valid=1 }
    $0 == begin { begins++; if (open) valid=0; open=1; next }
    $0 == end { ends++; if (!open) valid=0; open=0; next }
    END { exit !(begins == 1 && ends == 1 && !open && valid != 0) }
  ' "$file"
}

profile_has_any_marker() {
  local file="$1"
  [[ -f "$file" ]] && grep -Fxe "$PROFILE_MARKER_BEGIN" -e "$PROFILE_MARKER_END" "$file" >/dev/null 2>&1
}

remove_profile_block() {
  local file="$1" tmp=""
  if ! profile_has_block "$file"; then
    if profile_has_any_marker "$file"; then
      warn "profile 标记块不完整或重复，已保留文件：$file"
      return 1
    fi
    return 0
  fi
  tmp="$(mktemp)"
  awk -v begin="$PROFILE_MARKER_BEGIN" -v end="$PROFILE_MARKER_END" '
    $0 == begin { skip=1; next }
    $0 == end { skip=0; next }
    skip != 1 { print }
  ' "$file" > "$tmp"
  cat "$tmp" > "$file"
  rm -f "$tmp"
  success "已移除启动配置块：$file"
}

wrapper_is_managed() {
  [[ -f "$CLAUDE_WRAPPER" ]] && grep -Fq 'CLAUDE_TEAM_WRAPPER' "$CLAUDE_WRAPPER" 2>/dev/null
}

show_config_preview() {
  local file=""
  if state_is_pending; then
    printf '[保留] 检测到 Node 阶段中断状态；安装尚未写入新配置，不清理既有配置\n'
    printf '[保留] %s（供诊断/重试）\n' "$INSTALL_STATE_FILE"
    return 0
  fi
  settings_action 1 || true
  while IFS= read -r file; do
    if profile_has_block "$file"; then printf '[删除] profile 标记块：%s\n' "$file"
    elif profile_has_any_marker "$file"; then printf '[无法确认] profile 标记块不完整或重复，保留：%s\n' "$file"; fi
  done < <(profile_candidates)
  if [[ "$env_is_managed" == "1" ]]; then printf '[删除] %s\n' "$ENV_FILE";
  elif [[ -f "$ENV_FILE" ]]; then printf '[保留] %s（缺少生成标记）\n' "$ENV_FILE"; fi
  if wrapper_is_managed; then printf '[删除] %s\n' "$CLAUDE_WRAPPER";
  elif [[ -f "$CLAUDE_WRAPPER" ]]; then printf '[保留] %s（缺少 wrapper 标记）\n' "$CLAUDE_WRAPPER"; fi
  if state_is_pending; then
    printf '[保留] %s（安装曾在 Node 阶段中断，保留以供诊断/重试）\n' "$INSTALL_STATE_FILE"
  elif [[ -f "$INSTALL_STATE_FILE" ]]; then
    printf '[删除] %s（全部选定步骤成功后）\n' "$INSTALL_STATE_FILE"
  fi
  return 0
}

cleanup_config() {
  local preserve_state="${1:-0}"
  local file="" profile_failed="0"
  if state_is_pending; then
    warn "检测到 Node 阶段中断状态；安装尚未写入新配置，将保留既有配置和状态文件。"
    return 0
  fi
  settings_action 0 || return 1
  while IFS= read -r file; do remove_profile_block "$file" || profile_failed="1"; done < <(profile_candidates)
  [[ "$profile_failed" == "0" ]] || return 1
  if [[ "$env_is_managed" == "1" ]]; then rm -f "$ENV_FILE"; success "已删除环境文件：$ENV_FILE"; fi
  if wrapper_is_managed; then rm -f "$CLAUDE_WRAPPER"; success "已删除 wrapper：$CLAUDE_WRAPPER"; fi
  if [[ "$preserve_state" != "1" ]]; then rm -f "$INSTALL_STATE_FILE"; fi
  rmdir "$WRAPPER_DIR" 2>/dev/null || true
  rmdir "$CONFIG_DIR" 2>/dev/null || true
}

npm_prefix_for_install() {
  local prefix=""
  prefix="$(state_value npm.installPrefix || true)"
  if [[ -z "$prefix" ]] && need_cmd npm; then prefix="$(npm config get prefix 2>/dev/null || true)"; fi
  printf '%s' "$prefix"
}

package_version_at_prefix() {
  local prefix="$1"
  need_cmd npm && load_node_runtime || return 0
  npm_config_prefix="$prefix" npm list -g "$CLAUDE_NPM_PACKAGE_NAME" --depth=0 --json 2>/dev/null | node -e '
let s=""; process.stdin.on("data",c=>s+=c); process.stdin.on("end",()=>{try{const d=JSON.parse(s||"{}");const p=d.dependencies&&d.dependencies[process.argv[1]];if(p&&p.version)process.stdout.write(p.version)}catch{}})' "$CLAUDE_NPM_PACKAGE_NAME"
}

uninstall_package_at_prefix() {
  local prefix="$1"
  load_node_runtime || true
  need_cmd npm || { warn "未检测到 npm，无法卸载 Claude Code。"; return 1; }
  info "卸载 Claude Code npm 包（prefix: ${prefix:-current}）"
  if [[ -n "$prefix" ]]; then npm_config_prefix="$prefix" npm uninstall -g "$CLAUDE_NPM_PACKAGE_NAME"
  else npm uninstall -g "$CLAUDE_NPM_PACKAGE_NAME"; fi
}

npm_prefix_candidates() {
  local recorded="" current="" version_dir=""
  load_node_runtime || true
  recorded="$(npm_prefix_for_install)"
  if need_cmd npm; then current="$(npm config get prefix 2>/dev/null || true)"; fi
  printf '%s\n' "$recorded" "$current"
  for version_dir in "$HOME/.nvm"/versions/node/*; do
    [[ -f "$version_dir/lib/node_modules/@anthropic-ai/claude-code/package.json" ]] && printf '%s\n' "$version_dir"
  done
  if [[ -f "$HOME/.npm-global/lib/node_modules/@anthropic-ai/claude-code/package.json" ]]; then
    printf '%s\n' "$HOME/.npm-global"
  fi
}

full_uninstall_package() {
  local prefix=""
  load_node_runtime || true
  need_cmd npm || { warn "未检测到 npm，无法卸载 Claude Code。"; return 1; }
  while IFS= read -r prefix; do
    [[ -n "$prefix" ]] || continue
    uninstall_package_at_prefix "$prefix" || return 1
  done < <(npm_prefix_candidates | awk 'NF && !seen[$0]++')
}

restore_package_and_defaults() {
  [[ -f "$INSTALL_STATE_FILE" ]] || { warn "缺少安装状态，无法安全恢复 npm 包和运行时默认值；将只清理配置。"; return 0; }
  local known="" before_present="" before_version="" installed_version="" prefix="" current_version=""
  known="$(state_value npm.packageBeforeKnown)"
  prefix="$(npm_prefix_for_install)"
  if [[ "$known" == "true" ]]; then
    before_present="$(state_value npm.packageBeforePresent)"
    before_version="$(state_value npm.packageBeforeVersion)"
    installed_version="$(state_value npm.installedVersion)"
    load_node_runtime || true
    need_cmd npm || { warn "未检测到 npm，无法恢复 Claude Code 包；安装状态将保留。"; return 1; }
    current_version="$(package_version_at_prefix "$prefix" || true)"
    if [[ -n "$installed_version" && "$current_version" != "$installed_version" ]]; then
      warn "当前 Claude Code 版本已被修改（${current_version:-未安装}），将保留而不覆盖。"
    elif [[ "$before_present" == "true" && -n "$before_version" ]]; then
      info "恢复 Claude Code npm 版本：$before_version"
      npm_config_prefix="$prefix" npm install -g "$CLAUDE_NPM_PACKAGE_NAME@$before_version"
    else
      uninstall_package_at_prefix "$prefix"
    fi
  else
    warn "安装前 npm 包状态未知，将保留当前 Claude Code。"
  fi

  local prefix_changed="" prefix_before="" current_prefix=""
  prefix_changed="$(state_value npm.prefixChanged)"
  prefix_before="$(state_value npm.prefixBefore)"
  if [[ "$prefix_changed" == "true" && -n "$prefix_before" ]]; then
    load_node_runtime || true
    need_cmd npm || { warn "未检测到 npm，无法恢复 npm prefix；安装状态将保留。"; return 1; }
    current_prefix="$(npm config get prefix 2>/dev/null || true)"
    if [[ "$current_prefix" == "$prefix" ]]; then
      npm config set prefix "$prefix_before"
      success "已恢复 npm prefix：$prefix_before"
    else
      warn "npm prefix 已被用户修改，将保留：$current_prefix"
    fi
  fi

  local default_changed="" default_known="" default_before=""
  default_changed="$(state_value runtime.defaultChangedByBootstrap)"
  default_known="$(state_value runtime.defaultBeforeKnown)"
  default_before="$(state_value runtime.defaultBefore)"
  export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [[ "$default_changed" == "true" && "$default_known" == "true" && -s "$NVM_DIR/nvm.sh" ]]; then
    # shellcheck disable=SC1090
    . "$NVM_DIR/nvm.sh" >/dev/null 2>&1
    if [[ -n "$default_before" ]]; then nvm alias default "$default_before" >/dev/null
    else nvm unalias default >/dev/null 2>&1 || true; fi
  fi
}

runtime_has_untracked_content() {
  local nvm_dir="$1" version_dir="" version_name="" packages="" version_count=0 status_line="" status_path="" expected_inventory="" current_inventory=""
  expected_inventory="$(state_value runtime.inventoryAfter)"
  current_inventory="$(runtime_inventory_hash "$nvm_dir" 2>/dev/null || true)"
  if [[ -z "$expected_inventory" || -z "$current_inventory" || "$expected_inventory" != "$current_inventory" ]]; then
    warn "nvm 目录内容与安装完成时的清单不一致，已保留运行时。"
    return 0
  fi
  for version_dir in "$nvm_dir"/versions/node/*; do
    [[ -d "$version_dir" ]] || continue
    version_count=$((version_count + 1))
    version_name="$(basename "$version_dir")"
    [[ "$version_name" == v22.* ]] || { warn "检测到额外 Node 版本：$version_name"; return 0; }
    packages="$("$version_dir/bin/npm" list -g --depth=0 --parseable 2>/dev/null || true)"
    if printf '%s\n' "$packages" | awk 'NR>1 && $0 !~ /\/node_modules\/(npm|corepack)$/ && $0 !~ /\/node_modules\/@anthropic-ai\/claude-code$/ {found=1} END{exit !found}'; then
      warn "Node $version_name 中存在其他全局 npm 包。"
      return 0
    fi
  done
  if [[ "$version_count" -ne 1 ]]; then
    warn "Node 运行时数量不是脚本安装时的单一 Node 22，无法确认归属。"
    return 0
  fi
  if [[ "$(state_value runtime.managerInstalledByBootstrap)" == "true" ]]; then
    if ! need_cmd git || [[ ! -d "$nvm_dir/.git" ]]; then
      warn "无法使用 git 核对 nvm 目录内容，已保留运行时。"
      return 0
    fi
    while IFS= read -r status_line; do
      [[ -n "$status_line" ]] || continue
      status_path="${status_line:3}"
      if [[ "$status_line" == '?? '* ]] && [[ "$status_path" == .cache/* || "$status_path" == alias/default || "$status_path" == alias/lts/* || "$status_path" == versions/node/v22.*/* ]]; then
        continue
      fi
      warn "nvm 目录包含未记录的修改或文件：$status_line"
      return 0
    done < <(git -C "$nvm_dir" status --porcelain --untracked-files=all 2>/dev/null || printf '! git status failed\n')
  fi
  return 1
}

cleanup_runtime() {
  [[ -f "$INSTALL_STATE_FILE" ]] || { warn "缺少安装状态，不清理 Node 运行时。"; return 0; }
  if state_is_pending; then
    warn "安装状态尚未完成，无法确认部分安装的运行时归属；保留运行时和安装状态供重试或诊断。"
    return 1
  fi
  local manager_owned="" node_owned="" nvm_dir=""
  manager_owned="$(state_value runtime.managerInstalledByBootstrap)"
  node_owned="$(state_value runtime.node22InstalledByBootstrap)"
  [[ "$manager_owned" == "true" || "$node_owned" == "true" ]] || { warn "没有可确认由脚本安装的 Node 运行时。"; return 0; }
  local reply=""
  read_user_input -r -p "请输入 REMOVE NODE RUNTIME 确认清理脚本安装的运行时：" reply || true
  [[ "$reply" == "REMOVE NODE RUNTIME" ]] || { warn "未确认，保留 Node 运行时和安装状态。"; return 1; }
  nvm_dir="${NVM_DIR:-$HOME/.nvm}"
  [[ "$nvm_dir" == "$HOME/.nvm" ]] || { warn "NVM_DIR 不是默认用户目录，出于安全考虑不自动删除：$nvm_dir"; return 1; }
  if runtime_has_untracked_content "$nvm_dir"; then
    warn "运行时包含后续新增内容，已保留。"
    return 1
  fi
  if [[ "$manager_owned" == "true" ]]; then
    rm -rf -- "$nvm_dir"
    success "已删除脚本安装的 nvm：$nvm_dir"
  elif [[ "$node_owned" == "true" && -s "$nvm_dir/nvm.sh" ]]; then
    # shellcheck disable=SC1090
    . "$nvm_dir/nvm.sh" >/dev/null 2>&1
    nvm uninstall 22
  else
    warn "无法定位状态中记录的 Node 运行时，已保留安装状态。"
    return 1
  fi
}

purge_user_data() {
  [[ -d "$CLAUDE_DATA_DIR" ]] || { info "Claude 用户数据目录不存在：$CLAUDE_DATA_DIR"; return 0; }
  local size="unknown" reply=""
  if need_cmd du; then size="$(du -sh "$CLAUDE_DATA_DIR" 2>/dev/null | awk '{print $1}')"; fi
  warn "将永久删除 Claude 用户数据：$CLAUDE_DATA_DIR（大小：${size:-unknown}）"
  read_user_input -r -p "请输入 DELETE CLAUDE DATA 确认：" reply || true
  [[ "$reply" == "DELETE CLAUDE DATA" ]] || { warn "未确认，保留 Claude 用户数据。"; return 0; }
  [[ "$CLAUDE_DATA_DIR" == "$HOME/.claude" ]] || fatal "用户数据路径校验失败，拒绝删除：$CLAUDE_DATA_DIR"
  rm -rf -- "$CLAUDE_DATA_DIR"
  success "已删除 Claude 用户数据。"
}

report_unknown_claude() {
  local found=""
  found="$(command -v claude 2>/dev/null || true)"
  if [[ -n "$found" && "$found" != "$CLAUDE_WRAPPER" ]]; then
    warn "仍检测到其他渠道的 claude 命令，未自动删除：$found"
  fi
}

show_plan() {
  local mode="$1" runtime="$2" purge="$3" prefix="" version=""
  printf '\n============================================================\n'
  printf 'Claude Bootstrap 卸载预览\n'
  printf '============================================================\n'
  show_config_preview
  if [[ "$mode" == "restore" ]]; then
    printf '[恢复] npm 包、npm prefix 和默认 Node（仅限状态可确认且当前值未修改）\n'
  elif [[ "$mode" == "full" ]]; then
    while IFS= read -r prefix; do
      [[ -n "$prefix" ]] || continue
      version="$(package_version_at_prefix "$prefix" || true)"
      printf '[删除] npm Claude Code：%s（prefix: %s）\n' "${version:-未检测到}" "$prefix"
    done < <(npm_prefix_candidates | awk 'NF && !seen[$0]++')
  fi
  [[ "$runtime" == "1" ]] && printf '[高级] 清理状态确认属于脚本的 Node 运行时\n'
  [[ "$purge" == "1" ]] && printf '[危险] 删除全部 Claude 用户数据：%s\n' "$CLAUDE_DATA_DIR"
  printf '============================================================\n\n'
}

execute_mode() {
  local mode="$1" runtime="$2" purge="$3"
  load_managed_env
  show_plan "$mode" "$runtime" "$purge"
  [[ "$mode" == "preview" ]] && return 0
  confirm "确认执行以上操作？" || { info "已取消。"; return 0; }

  if [[ "$mode" == "restore" ]]; then restore_package_and_defaults || return 1
  elif [[ "$mode" == "full" ]]; then full_uninstall_package || return 1; fi
  cleanup_config "$runtime" || return 1
  if [[ "$runtime" == "1" ]]; then
    cleanup_runtime || return 1
    rm -f "$INSTALL_STATE_FILE"
    rmdir "$WRAPPER_DIR" 2>/dev/null || true
    rmdir "$CONFIG_DIR" 2>/dev/null || true
  fi
  if [[ "$purge" == "1" ]]; then purge_user_data; fi
  report_unknown_claude
  success "卸载操作完成。请重新打开终端使环境变化完全生效。"
}

choose_menu() {
  printf '\n请选择操作：\n'
  printf '  1) 预览将要清理的内容\n'
  printf '  2) 仅撤销 claude-bootstrap 配置 [默认]\n'
  printf '  3) 恢复安装前状态\n'
  printf '  4) 彻底卸载 Claude Code\n'
  printf '  5) 高级清理\n'
  printf '  6) 退出\n'
  local choice=""
  read_user_input -r -p "请输入编号 [2]: " choice || true
  case "${choice:-2}" in
    1) execute_mode preview 0 0 ;;
    2) execute_mode config 0 0 ;;
    3) execute_mode restore 0 0 ;;
    4) execute_mode full 0 0 ;;
    5) choose_advanced_menu ;;
    6) info "已退出。" ;;
    *) fatal "无效选择：$choice" ;;
  esac
}

choose_advanced_menu() {
  printf '\n高级清理：\n'
  printf '  1) 完整卸载并清理脚本安装的 Node 运行时\n'
  printf '  2) 完整卸载并删除全部 Claude 用户数据\n'
  printf '  3) 完整卸载、清理运行时并删除用户数据\n'
  printf '  4) 返回\n'
  local choice=""
  read_user_input -r -p "请输入编号 [4]: " choice || true
  case "${choice:-4}" in
    1) execute_mode full 1 0 ;;
    2) execute_mode full 0 1 ;;
    3) execute_mode full 1 1 ;;
    4) choose_menu ;;
    *) fatal "无效选择：$choice" ;;
  esac
}

main() {
  local mode="" runtime="0" purge="0"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --preview) [[ -z "$mode" ]] || fatal "只能选择一种主操作。"; mode="preview" ;;
      --config-only) [[ -z "$mode" ]] || fatal "只能选择一种主操作。"; mode="config" ;;
      --restore) [[ -z "$mode" ]] || fatal "只能选择一种主操作。"; mode="restore" ;;
      --full) [[ -z "$mode" ]] || fatal "只能选择一种主操作。"; mode="full" ;;
      --runtime) runtime="1" ;;
      --purge-data) purge="1" ;;
      -h|--help)
        printf 'Usage: uninstall.sh [--preview|--config-only|--restore|--full [--runtime] [--purge-data]]\n'
        return 0
        ;;
      *) fatal "未知参数：$1" ;;
    esac
    shift
  done
  if [[ "$runtime" == "1" || "$purge" == "1" ]]; then
    [[ "$mode" == "full" ]] || fatal "--runtime 和 --purge-data 必须与 --full 一起使用。"
  fi
  if [[ -n "$mode" ]]; then execute_mode "$mode" "$runtime" "$purge"
  else choose_menu; fi
}

main "$@"
